version: '3.8'

services:
  proxy:
    build: ./proxy
    ports:
      - "8000:8000"
    depends_on:
      - server
    networks:
      - app-net

  server:
    build: ./server
    env_file:
      - .env
    # Port 8080 tidak diekspos ke host, hanya bisa diakses dari dalam network docker
    expose:
      - "8080"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge